// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnuzpzizrkrawfcvkmsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudXpweml6cmtyYXdmY3ZrbXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTI2NTgsImV4cCI6MjA1ODI4ODY1OH0.u7R4y8wFSGpJkZAY8B-JQ2YKBvIp5dlWY_XhQ4u-NQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);